=== dave-masorn/SGF-Auditor/red-bean/red-bean.com/sgf/xml/sgfml/sgfml-0.01.dtd
<!-- =============================================================
	sgfml: Smart Game Format - XML DTD
	V0.01 *draft*
     =============================================================

	Arno Hollosi, ahollosi@mail.com

	Published as OpenContent
	OpenContent Licence: http://www.opencontent.org/opl

     ============================================================= -->


<!-- Elementary entities ========================================= -->

<!ENTITY lt     "&#38;#60;">
<!ENTITY gt     "&#62;">
<!ENTITY amp    "&#38;#38;">
<!ENTITY apos   "&#39;">
<!ENTITY quot   "&#34;">


<!-- Node structure ============================================== -->

<!ELEMENT sgfml ( (header)?, (game)+ )>
<!ATTLIST sgfml
	version CDATA #REQUIRED
>
<!ELEMENT game ( (header)?, sequence )>
<!ATTLIST game
	type (GO|CHESS|GOMUKU|LOA|HEX|AMAZONS) #REQUIRED
>
<!ELEMENT sequence ( (node)+, (sequence)* )>

<!-- fixme: ANY is sloppy -->
<!ELEMENT node ANY>
<!ELEMENT header ANY>


<!-- Header properties =========================================== -->

<!ELEMENT board EMPTY>
<!ATTLIST board
	size CDATA #IMPLIED
>
<!ELEMENT application EMPTY>
<!ATTLIST application
	name CDATA #REQUIRED
	version CDATA #REQUIRED
>

<!-- Properties ================================================== -->

<!ELEMENT move EMPTY>
<!ATTLIST move
	side CDATA #REQUIRED
	move CDATA #REQUIRED
	number CDATA #IMPLIED
	timeleft CDATA #IMPLIED
	timeused CDATA #IMPLIED
	annotate (VERYGOOD|GOOD|INTERESTING|DOUBTFUL|BAD|VERYBAD) #IMPLIED
	who CDATA #IMPLIED
>
	<!-- who ... if more than one person per side -->

<!ELEMENT point EMPTY>
<!ATTLIST point
	point CDATA #REQUIRED
	label CDATA #IMPLIED
>
	<!-- label ... only in combination with markup -->

<!ELEMENT stone EMPTY>
<!ATTLIST stone
	point CDATA #REQUIRED
	side CDATA #REQUIRED
	figure CDATA #IMPLIED
>
	<!-- figure ... for games with different figures -->

<!ELEMENT setup ( (stone)+ )>
<!ATTLIST setup
	sidetoplay CDATA #IMPLIED
>
	
<!ELEMENT comment (#PCDATA|br)* >
<!ELEMENT title (#PCDATA)>
<!ELEMENT br EMPTY>	<!-- linebreak -->

<!ELEMENT annotate EMPTY>
<!ATTLIST annotate
	type (GOOD|BAD|EVENPOS|UNCLEARPOS|HOTSPOT) #REQUIRED
	emphasis (NONE|YES) 'NONE'
	side CDATA #IMPLIED
>

<!ELEMENT value (#PCDATA) >

<!ELEMENT markup ( (point)+ )>
<!ATTLIST markup
	type (MARK|TRIANGLE|CIRCLE|RECTANGLE|VIEW|DIM|LABEL|TERRITORY) 'MARK'
	side CDATA #IMPLIED
>
	<!-- side ... only for territory markup -->


<!ELEMENT line ( (point, point)+ )>
<!ATTLIST line
	type (LINE|ARROW) 'LINE'
>


<!-- Game-Info properties ======================================== -->

<!-- fixme: these are just dummy definitions -->

<!ELEMENT event ( #PCDATA )>
<!ELEMENT round ( #PCDATA )>
<!ELEMENT place ( #PCDATA )>
<!ELEMENT source ( #PCDATA )>
<!ELEMENT copyright ( #PCDATA )>
<!ELEMENT opening ( #PCDATA )>
<!ELEMENT rules ( #PCDATA )>
<!ELEMENT result ( #PCDATA )>
<!ELEMENT time ( #PCDATA )>
<!ELEMENT date ( #PCDATA )>
<!ELEMENT komi ( #PCDATA )>
<!ELEMENT handicap ( #PCDATA )>


<!-- Properties for description of people ======================== -->

<!ELEMENT people (name, (rating|contact)* )>
<!ATTLIST people
	role (PLAYER|ANNOTATOR|RECORDER) #REQUIRED
	side CDATA #IMPLIED
	team CDATA #IMPLIED
>
	<!-- team ... id of team -->

<!ELEMENT name (#PCDATA) >
<!ELEMENT rating (#PCDATA) >
<!ATTLIST rating
	body CDATA #IMPLIED
>
	<!-- body ... organization or place -->

<!ELEMENT contact (#PCDATA) >
<!ATTLIST contact
	type (EMAIL|ADDRESS|PHONE) 'EMAIL'
>

<!ELEMENT team ( #PCDATA )>
<!ATTLIST team
	id CDATA #REQUIRED
>


<!-- Dummy property ============================================== -->

<!ELEMENT property (#PCDATA) >
<!ATTLIST property
	name CDATA #REQUIRED
>

=== dave-masorn/SGF-Auditor/red-bean/red-bean.com/sgf/xml/sgfml/review-001.xml
<?xml version="1.0" ?>
<!DOCTYPE sgfml SYSTEM "http://www.red-bean.com/sgf/xml/sgfml-0.01.dtd">

<sgfml version='0.01'>
<header>
	<application name='SGFC' version='1.14'/>
</header>

<game type='GO'>
<header>
	<board size='19x19'/>
</header>

<sequence>
<node>
	<event>7th Three Peaks Go Tournament</event>

	<people role='PLAYER' side='B'>
		<name>david philips, Isle of Man</name>
		<rating>2 dan</rating>
	</people>
	<people role='PLAYER' side='W'>
		<name>djna (dave artus), London</name>
		<rating>1 dan</rating>
	</people>

	<date>1999-11-13</date>
	<place>Thornton in Lonsdale</place>
	<komi>5.5</komi>
	<result>B+R</result>

	<comment>I had W in this game, thought I had parity for
much of it and ended up resigning in the yose on finding
myself 20 points or more behind.
<br/><br/>
I'd like to understand where my perceptions went awry.
<br/><br/>
David (Philips) played what felt to me to be quietly effective
moves and it appears was never really stretched.
	</comment>
</node>

<node><move side='B' move='dp'/></node>
<node><move side='W' move='pd'/></node>
<node><move side='B' move='qp'/></node>

  <sequence>
  <node><move side='W' move='op'/>
	<comment>My new policy of refusing to allow Chinese Fuseki.
<br/><br/>
JS: Another idea is to play this move one point to the left.
See variation.</comment>
  </node>
  <node><move side='B' move='pn'/></node>
  <node><move side='W' move='qq'/></node>
  <node><move side='B' move='rq'/></node>
  <node><move side='W' move='pq'/></node>
  <node><move side='B' move='ro'/></node>
  <node><move side='W' move='lq'/>
	<comment>Seems pretty much a one-way street, unless I
ignore 5 and take the empty corner.
<br/><br/>
JS: If you want to play tenuki after black 5 (the keima)
then I would prefer to play the move I suggested in the variation.
But tenuki surely is an option as well.</comment>
  </node>
  <node><move side='B' move='dc'/></node>

    <sequence>
    <node><move side='W' move='de'/>
	  <markup type='MARK'><point point='cj'/></markup>
	  <markup type='LABEL'><point point='qf' label='A'/></markup>
	  <comment>I suspect I know what's coming, but is there really
a better appraoch move? Or a move around the triangle?
<br/><br/>
JS: A move at c10 is a lesurely approach, it's ok to play like that.
<br/><br/>
JS: The theory is that making or preventing a shimari always
is a big move in the opening. But the shape in the lower-right
has quite some consequences for the dirrection of play.
White's shape along the bottom is very solid, which means that
any move played by black in that direction is less effective since
it doesn't affect white. Black's shape along the right side is strong
so black very much would like to approach the white hoshi stone
in the upper-right at A (r14) to create a moyo.
Considering the whole board: when white can establish a position
along the left side (between the two black stones) it would be a success.
So now combining all these features gives a picture as in the
variation.</comment>
    </node>
    <node><move side='B' move='fd'/></node>
    <node><move side='W' move='cc'/></node>
    <node><move side='B' move='cb'/></node>
    <node><move side='W' move='cd'/></node>
    <node><move side='B' move='eb'/></node>
    <node><move side='W' move='ch'/>
	  <comment>On a policy of maintaining symmetry a 3-3 invasion
in the top right might be amusing. W could easily
end up with a wall whose thickness is erased by
a nice extension from the appropriate B group?
<br/><br/>
JS: In general by playing (3,3) here in the upper-right
black will harden white's shape while black would prefer
to leave white soft to be able to approach from both the
right side and the top. But anyway, I investigated some
(3,3) variations.</comment>
    </node>

      <sequence>
      <node><move side='B' move='qf'/></node>
      <node><move side='W' move='nc'/></node>
      <node><move side='B' move='rd'/></node>
      <node><move side='W' move='qc'/></node>
      <node><move side='B' move='qi'/>
	    <comment>If black plays like this then playing
r11 or q11 immediately seems better to leave the option to
invade r17.</comment>
      </node>

	<sequence>
	<node><move side='W' move='kc'/>
	      <comment>This is a move I'm not sure about.
My thinking was that if I go a more normal extra point
to the left then a B splitting  invasion would be troublesome.
If I play elsewhere then B gets a good extension to the
the right of 24.
<br/><br/>
The way I played was intended to make it hard to develop
anything from the top left and leave me solid enough to
be more aggressive elsewhere.
<br/><br/>
JS: This move is big (preventing black m17) and correct shape.
But there are bigger moves. Opening theory says that in sente situations
(as you have in this position) the focus in the opening goes
to the largest empty space (i.e. the lower-left). See variation
for an example.</comment>
	</node>
	<node><move side='B' move='fq'/>
<comment>Seems like a nice move. I felt that I needed to do
something to keep the bottom left under control.</comment></node>

	  <sequence>
	  <node><move side='W' move='bo'/>
		<markup type='LABEL'><point point='bp' label='A'/>
		<point point='cn' label='A'/></markup>
		<comment> I was expecting moves at A or B, and I
reckoned that either would suit me.
<br/><br/>
JS: You don't need to play this emergency move. If black
would have a stone around c10 then this would have been
a possible way to invade. But since your left side is extremely
strong just aproaching with the normal move at B seems best.
See variation.</comment>
	  </node>
	  <node><move side='B' move='cq'/>
		<markup type='LABEL'><point point='cm' label='A'/></markup>
		<markup type='MARK'><point point='cm' label='A'/></markup>
		<comment> Hmm, a move at the square seems to ask to be
pincered, and all I want is to stop the B corner getting too big
too fast. So, I'll treat 26/27 as kikashi.
<br/><br/>
Q: Is that reasoning OK?
<br/><br/>
JS: A kikashi move doesn't cost points, but I think you loose
points here. b5 is very low and c3 prevents an invasion.</comment>
	  </node>
	  <node><move side='W' move='ck'/>
		<markup type='LABEL'><point point='cm' label='A'/>
		<point point='cn' label='B'/></markup>
		<comment>So I play here. The idea is that B needs to spend
2 moves to increase his territory by 5 points. He can't
play A (I think) so he has to play B and that's too slow.
<br/><br/>
JS: c9 is a good move, but without the b5/c3 exchange.
After immediately c9 you still have the c3 invasion or
moves like c6 or c4. The extra black stone at c3 made black
stronger which also makes the bottom different. White h3
is gote in this shape so black might have more chance to
get j3 or k3 here.</comment>
	  </node>
	  <node><move side='B' move='cn'/>
		<markup type='LABEL'><point point='fn' label='A'/></markup>
		<comment>Hmm, so one of us is wrong!
<br/><br/>
I assume that it's me, and the reason is that 29 is also building
influence towards C.
<br/><br/>
Q: Was it too slow?
<br/><br/>
JS: Black's last move adds stones to a strong position so it's
not a very good move. Please note that if white later defends
with c7 then white played three moves on the left side while
he could have played two moves (c6 and c9), so the left side
is not urgent at all. Black k3 seems bigger for example or
black q15 (to prevent being flattened by white with q12+q14).
At the top j17 (preventing white h17) is big.</comment>
	  </node>
	  <node><move side='W' move='iq'/>
		<comment>a B extension this way seems big after 29.
<br/><br/>
JS: Correct.</comment>
	  </node>
	  <node><move side='B' move='no'/>
		<comment>This move is gote (see variation) so this is a
chance for you to develop the top.</comment>
	  </node>

	    <sequence>
	    <node><move side='W' move='np'/>
		  <comment>Now black's move at o5 is a kikashi
(black gains here).</comment>
	    </node>
	    <node><move side='B' move='md'/></node>
	    <node><move side='W' move='mc'/></node>
	    <node><move side='B' move='oe'/>
		  <markup type='LABEL'><point point='pe' label='A'/>
			<point point='pf' label='B'/>
			<point point='of' label='C'/></markup>
		  <comment>It's at this point that I estimated the
scores in detail to decide how deep to go.
<br/><br/>
I've got half an eye on pushing and cutting D, E, F
<br/><br/>
JS: The black shape is a bit thin, maybe I would prefer Q15
immediately instead of the last two black moves.
<br/><br/>
About the territorial balance here:
<br/><br/>
 White: LR: 17, UL: 17, UR: 17, komi: 5.5<br/>
 Black: LL: 20, UL: 5
<br/><br/>
So for black to win the right side has to become at least 30 points.
Please note that at the top the n16/n17 exchange makes black j17
smaller so you have a good chance to get h17 in this position
(although I didn't assume that during the counting).</comment>
	    </node>
	    <node><property name='FG'></property></node>
	    <node><move side='W' move='nj'/>
		  <comment>Based on the idea that B does not get enough when
he seals off the side
<br/><br/>
JS: Nice move. Let's see if black would convert the right side
how many points he would get there...</comment>
	    </node>

	      <sequence>
	      <node><move side='B' move='pk'/>
		    <comment>But again B seems entirely happy to take
the money.
<br/><br/>
JS: This move is very similar to black q10.
My feeling is that this move is too submissive.
As black I would either play p11 (as discussed before)
or attack with m10. Another move which black might
consider is p9 by the way.</comment>
	      </node>

		<sequence>
		<node><move side='W' move='mo'/>
		      <comment>JS: A move interesting way to play might be as
in the variation diagram.</comment>
		</node>
		<node><move side='B' move='nn'/></node>
		<node><move side='W' move='mn'/></node>
		<node><move side='B' move='nm'/></node>

		  <sequence>
		  <node><move side='W' move='gp'/>
			<comment>Another suspect move
<br/><br/>
JS: Once you start to push with n6 you have to finish the
shape there, see variation.</comment>
		  </node>
